theme:
title: Hi, I'm Spencer.
description: Computer Science major at the University of California, Irvine class of 2021
github_username: spencerericfong
resume: https://drive.google.com/open?id=1fAEh94tmDmJVj-SQa-c8poE5M7ZE4O5n
url: https://spencerericfong.github.io/
github:
  is_project_page: true
