theme:
title: Hi, I'm Spencer.
description: Computer Science major at the University of California, Irvine class of 2021
github_username: spencerericfong
resume: https://drive.google.com/file/d/1VEWo8cRgQTWFygvuALhp8FISosGvRj-S/view?usp=sharing
url: https://spencerericfong.github.io/
github:
  is_project_page: true
