theme:
title: Hi, I'm Spencer.
description: Computer Science major at the University of California, Irvine class of 2021
github_username: spencerericfong
resume: https://drive.google.com/file/d/1F3JsSkUqXV3yM3bj7JKCcpr78rTucY6F/view?usp=sharing
github:
  is_project_page: true
