theme:
title: Hi, I'm Spencer.
description: Computer Science major at the University of California, Irvine class of 2021
github_username: spencerericfong
url: "https://spencerericfong.github.io"
author: "Spencer Eric Fong"
image: "/assets/pictures/spencer_profile.jpg"
github:
  is_project_page: true
