theme:
title: Hi, I'm Spencer.
description: Computer Science major at the University of California, Irvine class of 2021
github_username: spencerericfong
resume: https://drive.google.com/open?id=1VEWo8cRgQTWFygvuALhp8FISosGvRj-S
url: https://spencerericfong.github.io/
github:
  is_project_page: true
