theme:
title: Hi, I'm Spencer.
description: Computer Science major at the University of California, Irvine class of 2021
github_username: spencerericfong
resume: /assets/Spencer's_Resume.pdf
github:
  is_project_page: true
