theme: jekyll-theme-cayman
title: Spencer Eric Fong
email: spencerericfong@gmail.com
description: Here you'll find my projects, experiences, and other neat stuff about me.
github_username: spencerericfong
